security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern:  ^/demo/secured/login$
        #    security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /reviews
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            remember_me:
                name: peerreview
                key:      Ew6jlvD8qCrwZbiGf_U35UH9I
                lifetime: 2592000
                path:     /
                domain:   ~            

    access_control:
        # Parts available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        # Secured part of the site
        - { path: ^/, role: ROLE_USER }
