PxSPeerReviewingBundle_stats:
    pattern:  /stats
    defaults: { _controller: PxSPeerReviewingBundle:Statistics:stats }
    
PxSPeerReviewingBundle_dashboard:
    pattern:  /
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:reviews }
    
PxSPeerReviewingBundle_reviews:
    pattern:  /reviews
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:reviews }

PxSPeerReviewingBundle_reviews_new:
    pattern:  /reviews/new
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:new }
    
PxSPeerReviewingBundle_reviews_detail:
    pattern:  /reviews/{id}
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:detail }
    
PxSPeerReviewingBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:feedback }