PxSPeerReviewingBundle_homepage:
    pattern:  /
    defaults: { _controller: PxSPeerReviewingBundle:Homepage:index }

PxSPeerReviewingBundle_reviews:
    pattern:  /{user}/reviews
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:index }
    
PxSPeerReviewingBundle_peer_reviews:
    pattern:  /{user}/peer-reviews
    defaults: { _controller: PxSPeerReviewingBundle:PeerReviews:index }
    
    
PxSPeerReviewingBundle_reviews_detail:
    pattern:  /{user}/reviews/{review}
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:detail }