PxSPeerReviewingBundle_reviews:
    pattern:  /reviews
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:reviews }

PxSPeerReviewingBundle_reviews_detail:
    pattern:  /reviews/{review}
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:detail }
    
PxSPeerReviewingBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:feedback }