PxSPeerReviewingBundle_homepage:
    pattern:  /
    defaults: { _controller: PxSPeerReviewingBundle:Homepage:index }

PxSPeerReviewingBundle_dashboard:
    pattern:  /{user}
    defaults: { _controller: PxSPeerReviewingBundle:Dashboard:index }