PxSPeerReviewingBundle_homepage:
    pattern:  /
    defaults: { _controller: PxSPeerReviewingBundle:Homepage:index }

PxSPeerReviewingBundle_reviews:
    pattern:  /{user}/reviews
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:reviews }
    
PxSPeerReviewingBundle_peer_reviews:
    pattern:  /{user}/peer
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:peer }

PxSPeerReviewingBundle_reviews_detail:
    pattern:  /{user}/reviews/{review}
    defaults: { _controller: PxSPeerReviewingBundle:Reviews:detail }