parameters:
#    px_s_peer_reviewing.example.class: PxS\PeerReviewingBundle\Example

services:
#    px_s_peer_reviewing.example:
#        class: %px_s_peer_reviewing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
